[Theme]
DisplayName=KOS-MOS

[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\icons\system.ico

[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\icons\documents.ico

[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\icons\recycle.ico
Empty=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\icons\recycle.ico

[Control Panel\Desktop]
Wallpaper=D:\Coding\waifu-usage-monitor\wallpaper\kosmos-5k.png
TileWallpaper=0
WallpaperStyle=10

[Control Panel\Cursors]
Arrow=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\arrow.cur
IBeam=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\text.cur
Wait=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\busy.cur
AppStarting=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\working.cur
Crosshair=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\crosshair.cur
Hand=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\hand.cur
No=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\unavailable.cur
SizeAll=D:\Coding\waifu-usage-monitor\wallpaper\windows11-kosmos\cursors\move.cur

[VisualStyles]
Path=%ResourceDir%\Themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XFF35C7E8
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[Sounds]
SchemeName=KOSMOS

[MasterThemeSelector]
MTSM=DABJDKT
